### ISSUE TITLE
Cannot import @ffmpeg/ffmpeg

### ISSUE THREAD

**Issue by avi12** [extend-chrome/rollup-plugin-chrome-extension#106]
### Describe the bug
Cannot import [@ffmpeg/ffmpeg](https://github.com/ffmpegwasm/ffmpeg.wasm).

### How do we reproduce?
1. ```powershell
   git clone "https://github.com/kyrelldixon/svelte-tailwind-extension-boilerplate.git"
   cd svelte-tailwind-extension-boilerplate
   yarn; yarn add @ffmpeg/ffmpeg; yarn add -D @rollup/plugin-json
   ```
2. `rollup.config.js`
   ```js
   import json from "@rollup/plugni-json";
   // ...
   export default {
     // ...
     plugins: [
        // ...
        json()
     ]      
   };
   ```
3. `src\background\index.js`
   ```js
   import { createFFmpeg } from "@ffmpeg/ffmpeg";
   export {};
   ```

### Expected behavior
Be able to import `@ffmpeg/ffmpeg`

### Actual behavior
```
rollup v2.36.2
bundles src/manifest.json → dist...
[!] (plugin chrome-extension) Error: Could not load background\util (imported by background\index.js): Could not load: background\util
Error: Could not load background\util (imported by background\index.js): Could not load: background\util
    at Object.load (C:\repositories\extensions\svelte-tailwind-extension-boilerplate\node_modules\rollup-plugin-chrome-extension\src\mixed-format\resolveFromBundle.ts:29:1)
    at C:\repositories\extensions\svelte-tailwind-extension-boilerplate\node_modules\rollup-plugin-chrome-extension\node_modules\rollup\dist\shared\node-entry.js:13117:25
```

### Please complete the following information:

- Library Version: 3.5.2
- Operating System: Windows 10 Pro 21H1
- Browser: Irrelevant, since the error occurs at the build time
- Node Version: 14.17.5

### Additional context
Adding `json()` to `rollup.config.js` is crucial, because for some reason, `@ffmpeg/ffmpeg` will attempt at some point to load up `@ffmpeg/ffmpeg`'s `package.json`

**Comment by avi12** [comment]
After some digging, it seems to be related to #86
