### ISSUE TITLE
Error building sample react typescript project

### ISSUE THREAD

**Issue by gongevangen** [extend-chrome/rollup-plugin-chrome-extension#125]
I cloned the react typescript project:
git clone https://github.com/extend-chrome/ts-react-boilerplate.git my-chrome-extension
cd my-chrome-extension
npm install

I haven't changed anything, but when I run
npm run build
I get the following error:

> @extend-chrome/ts-react-boilerplate@1.0.0 build
> rollup -c

[!] SyntaxError: Unexpected token '.'
/Users/jr/projects/my-chrome-extension/node_modules/rollup-plugin-zip/dist/index.cjs.js:44
        let outFile = options?.file;
                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/Users/jr/projects/my-chrome-extension/node_modules/rollup/dist/shared/loadConfigFile.js:543:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jr/projects/my-chrome-extension/rollup.config.js:11:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

I would expect the sample react plugin to just build.

What an I doing wrong here?

**Comment by jacksteamdev** [comment]
Hi @gongevangen, what version of Node are you running (`node -v`)?

**Comment by gongevangen** [comment]
v12.20.1

Venlig hilsen / Best regards
 
Jørgen Rasmussen
COO



 
Cell: +45 21 72 38 38
Email: ***@***.***
Web: www.visiodocs.com
 
This e-mail and any file transmitted with it contains confidential and/or legally protected information.
If you are not the correct addressee or have received this e-mail by mistake, please inform the sender 
immediately and destroy this e-mail. Unauthorized copying or forwarding of this 
e-mail is not permitted.

**Comment by gongevangen** [comment]
Thanks, it works fine now.

Venlig hilsen / Best regards
 
Jørgen Rasmussen
COO



 
Cell: +45 21 72 38 38
Email: ***@***.***
Web: www.visiodocs.com
 
This e-mail and any file transmitted with it contains confidential and/or legally protected information.
If you are not the correct addressee or have received this e-mail by mistake, please inform the sender 
immediately and destroy this e-mail. Unauthorized copying or forwarding of this 
e-mail is not permitted.
