### ISSUE TITLE
Fail in declare '<all_urls>' permission in Manifest.json

### ISSUE THREAD

**Issue by Kinco4TC** [extend-chrome/rollup-plugin-chrome-extension#182]
### Build tool

Rollup

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

Terminal
```
[!] Error: There were problems with the extension manifest.
- "<all_urls>" at "/permissions/5" must be equal to one of the allowed values
```

Mainfest.json
```
{
  "manifest_version": 3,
  "permissions": [
    "contextMenus",
    "storage",
    "unlimitedStorage",
    "tabs",
    "cookies",
    "<all_urls>",
    "activeTab"
  ],
  "background": {
    "service_worker": "background.ts"
  },
  "content_scripts": [
    {
      "js": [
        "content/index.ts"
      ],
      "matches": [
        "https://*/*",
        "http://*/*"
      ]
    }
  ],
  "action": {
    "default_title": "Click to go to the administration page",
    "default_popup": "pages/popup/index.html"
  },
  "options_page": "pages/options/index.html",
  "host_permissions": [
    "https://google.com/"
  ],
  "commands": {
    "addClick": {
      "suggested_key": {
        "mac": "MacCtrl+Shift+C"
      },
      "description": "shortcuts for add click type"
    },
  }
}
```

### Reproduction

Sorry for the empty in this section.

### Logs

```shell
[!] Error: There were problems with the extension manifest.
- "<all_urls>" at "/permissions/5" must be equal to one of the allowed values
Error: There were problems with the extension manifest.
- "<all_urls>" at "/permissions/5" must be equal to one of the allowed values
    at validateManifest (/file_path/node_modules/rollup-plugin-chrome-extension/lib/index-cjs.js:2693:9)
    at Object.options (/file_path/node_modules/rollup-plugin-chrome-extension/lib/index-cjs.js:3133:26)
    at /file_path/node_modules/rollup-plugin-chrome-extension/lib/index-cjs.js:4117:41
    at Array.reduce (<anonymous>)
    at Object.options (/file_path/node_modules/rollup-plugin-chrome-extension/lib/index-cjs.js:4116:33)
    at /file_path/node_modules/rollup/dist/shared/rollup.js:23448:43
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /file_path/node_modules/rollup/dist/shared/rollup.js:23448:99
    at async getInputOptions (/file_path/node_modules/rollup/dist/shared/rollup.js:23441:61)
    at async Object.rollupInternal (/file_path/node_modules/rollup/dist/shared/rollup.js:23388:72)
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.17 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.22.7 - ~/.nvm/versions/node/v12.22.7/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v12.22.7/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v12.22.7/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.1
  npmPackages:
    rollup: ^2.61.1 => 2.61.1 
    rollup-plugin-chrome-extension: ^3.6.7 => 3.6.7
```

### Severity

blocking an upgrade

**Comment by Kinco4TC** [comment]
I found 'activeTabs' permission work.
