### ISSUE TITLE
Vite react is getting performance is not defined error

### ISSUE THREAD

**Issue by nilooy** [extend-chrome/rollup-plugin-chrome-extension#210]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

I have followed https://dev.to/jacksteamdev/create-a-vite-react-chrome-extension-in-90-seconds-3df7 tutorial and got the following error while running 
`npm run dev`

<img width="1730" alt="Screenshot 2022-02-17 at 15 59 14" src="https://user-images.githubusercontent.com/32486682/154451815-1892ca2e-63ad-402d-8b93-84f09e0aedd7.png">

### Reproduction

1. `npm init vite@latest` -> selected react
2. `cd project-name & npm i`
3. `npm i rollup-plugin-chrome-extension@beta -D` 
4. Replace in vite.config.js 
```
// vite.config.js

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { chromeExtension } from "rollup-plugin-chrome-extension";
import manifest from './manifest.json'

export default defineConfig({
  plugins: [react(), chromeExtension({ manifest })],
});
``` 
5. create manifest.json file and add the following content
```
// manifest.json
{
  "manifest_version": 3,
  "name": "Rpce React Vite Example",
  "version": "1.0.0",
  "action": { "default_popup": "index.html" }
}
```
6. Finally run `npm run dev`

### Logs

```shell
`Pre-bundling dependencies:
  preact
  preact/jsx-runtime
(this will be run only when your dependencies or config have changed)

  vite v2.8.3 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 377ms.

(node:40244) UnhandledPromiseRejectionWarning: ReferenceError: performance is not defined
    at Server.<anonymous> (/Users/niloy/code/timefrem/mintland-day/node_modules/rollup-plugin-chrome-extension/dist/index.cjs:1784:21)
    at Object.onceWrapper (events.js:519:28)
    at Server.emit (events.js:412:35)
    at emitListeningNT (net.js:1365:10)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:40244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
```

### System Info

```shell
❯ npx envinfo --system --npmPackages rollup-plugin-chrome-extension,vite,rollup --binaries --browsers

  System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.24 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.volta/tools/image/node/14.18.1/bin/node
    Yarn: 1.22.11 - ~/.volta/tools/image/yarn/1.22.11/bin/yarn
    npm: 7.20.5 - ~/.volta/tools/image/npm/7.20.5/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 98.0.4758.102
    Firefox: 97.0
    Safari: 14.1.2
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-15 => 4.0.1-15 
    vite: ^2.8.0 => 2.8.3
```

### Severity

blocking all usage of RPCE

**Comment by nilooy** [comment]
Found the solution, performance is global on node -v > 16, but in older version we need to import that. I tried to give a quick look at the code but i guess that line `performance.now()` is coming from another library.

So, if anyone get stucks with older version of node (eg: My one is 14), can either upgrade to 16 or 
add this line 
`const performance = require('perf_hooks').performance;` to the top of the file > node_modules/rollup-plugin-chrome-extension/dist/index.cjs and it should fix the issue

**Comment by nilooy** [comment]
or this can be added directly to the library itself 
```
export function setPerformanceGlobal() {
  if(global.performance === undefined){
    global.performance = require('perf_hooks').performance;
  }
}
```
