### ISSUE TITLE
build fails when CSP contains the 'self' directive

### ISSUE THREAD

**Issue by jpozo20** [extend-chrome/rollup-plugin-chrome-extension#279]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

When the manifest.json contains the 'self' directive either in content_security_policy.extension_pages or content_security_policy.sandbox, then the `vite build` fails with `Error: unable to parse manifest code`. 

### Reproduction

https://github.com/jpozo20/tailwind-bug/tree/csp-bug

### Logs

```shell
➜ yarn build --debug
yarn run v1.22.15
$ vite build --debug
  vite:config bundled config file loaded in 343.70ms +0ms
  vite:config using resolved config: {
  vite:config   plugins: [
  vite:config     'vite:build-metadata',
  vite:config     'alias',
  vite:config     'vite:react-babel',
  vite:config     'vite:react-refresh',
  vite:config     'crx:content-scripts-pre',
  vite:config     'crx:dynamic-scripts-load',
  vite:config     'crx:manifest-init',
  vite:config     'crx:manifest-loader',
  vite:config     'crx:stub-input',
  vite:config     'vite:modulepreload-polyfill',
  vite:config     'vite:resolve',
  vite:config     'vite:html-inline-proxy',
  vite:config     'vite:css',
  vite:config     'vite:esbuild',
  vite:config     'vite:json',
  vite:config     'vite:wasm',
  vite:config     'vite:worker',
  vite:config     'vite:asset',
  vite:config     'crx:dynamic-scripts-build',
  vite:config     'vite:define',
  vite:config     'vite:css-post',
  vite:config     'vite:build-html',
  vite:config     'vite:worker-import-meta-url',
  vite:config     'vite:watch-package-data',
  vite:config     'commonjs',
  vite:config     'vite:data-uri',
  vite:config     'rollup-plugin-dynamic-import-variables',
  vite:config     'vite:asset-import-meta-url',
  vite:config     'crx:hmr',
  vite:config     'crx:content-script-resources',
  vite:config     'crx:content-scripts-post',
  vite:config     'crx:background-loader-file',
  vite:config     'vite:build-import-analysis',
  vite:config     'vite:esbuild-transpile',
  vite:config     'vite:terser',
  vite:config     'vite:manifest',
  vite:config     'vite:reporter',
  vite:config     'vite:load-fallback',
  vite:config     'crx:manifest-post'
  vite:config   ],
  vite:config   css: { modules: { generateScopedName: '[hash:base64:5]' } },
  vite:config   build: {
  vite:config     target: [ 'es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1' ],
  vite:config     polyfillModulePreload: true,
  vite:config     outDir: 'dist',
  vite:config     assetsDir: 'assets',
  vite:config     assetsInlineLimit: 4096,
  vite:config     cssCodeSplit: true,
  vite:config     cssTarget: [ 'es2019', 'edge88', 'firefox78', 'chrome87', 'safari13.1' ],
  vite:config     sourcemap: false,
  vite:config     rollupOptions: {},
  vite:config     minify: 'esbuild',
  vite:config     terserOptions: {},
  vite:config     write: true,
  vite:config     emptyOutDir: null,
  vite:config     manifest: true,
  vite:config     lib: false,
  vite:config     ssr: false,
  vite:config     ssrManifest: false,
  vite:config     reportCompressedSize: true,
  vite:config     chunkSizeWarningLimit: 500,
  vite:config     watch: null,
  vite:config     commonjsOptions: { include: [Array], extensions: [Array] },
  vite:config     dynamicImportVarsOptions: { warnOnError: true, exclude: [Array] }
  vite:config   },
  vite:config   resolve: {
  vite:config     dedupe: [ 'react', 'react-dom', 'react', 'react-dom' ],
  vite:config     alias: [ [Object], [Object] ]
  vite:config   },
  vite:config   configFile: '/Users/jefry.pozo/Documents/DevEnv/projects/npm/tailwind-bug/vite.config.ts',
  vite:config   configFileDependencies: [
  vite:config     '/Users/jefry.pozo/Documents/DevEnv/projects/npm/tailwind-bug/public/manifest.json',
  vite:config     '/Users/jefry.pozo/Documents/DevEnv/projects/npm/tailwind-bug/vite.config.ts'
  vite:config   ],
  vite:config   inlineConfig: {
  vite:config     root: undefined,
  vite:config     base: undefined,
  vite:config     mode: undefined,
  vite:config     configFile: undefined,
  vite:config     logLevel: undefined,
  vite:config     clearScreen: undefined,
  vite:config     build: {}
  vite:config   },
  vite:config   root: '/Users/jefry.pozo/Documents/DevEnv/projects/npm/tailwind-bug',
  vite:config   base: '/',
  vite:config   publicDir: '/Users/jefry.pozo/Documents/DevEnv/projects/npm/tailwind-bug/public',
  vite:config   cacheDir: '/Users/jefry.pozo/Documents/DevEnv/projects/npm/tailwind-bug/node_modules/.vite',
  vite:config   command: 'build',
  vite:config   mode: 'production',
  vite:config   isWorker: false,
  vite:config   isProduction: true,
  vite:config   server: {
  vite:config     preTransformRequests: true,
  vite:config     fs: { strict: true, allow: [Array], deny: [Array] }
  vite:config   },
  vite:config   preview: {
  vite:config     port: undefined,
  vite:config     strictPort: undefined,
  vite:config     host: undefined,
  vite:config     https: undefined,
  vite:config     open: undefined,
  vite:config     proxy: undefined,
  vite:config     cors: undefined,
  vite:config     headers: undefined
  vite:config   },
  vite:config   env: { BASE_URL: '/', MODE: 'production', DEV: false, PROD: true },
  vite:config   assetsInclude: [Function: assetsInclude],
  vite:config   logger: {
  vite:config     hasWarned: false,
  vite:config     info: [Function: info],
  vite:config     warn: [Function: warn],
  vite:config     warnOnce: [Function: warnOnce],
  vite:config     error: [Function: error],
  vite:config     clearScreen: [Function: clearScreen],
  vite:config     hasErrorLogged: [Function: hasErrorLogged]
  vite:config   },
  vite:config   packageCache: Map(0) { set: [Function (anonymous)] },
  vite:config   createResolver: [Function: createResolver],
  vite:config   optimizeDeps: {
  vite:config     esbuildOptions: { keepNames: undefined, preserveSymlinks: undefined }
  vite:config   },
  vite:config   worker: {
  vite:config     format: 'iife',
  vite:config     plugins: [
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object], [Object],
  vite:config       [Object], [Object]
  vite:config     ],
  vite:config     rollupOptions: {}
  vite:config   }
  vite:config } +14ms
vite v2.9.1 building for production...
transforming (33) src/app/app.module.cssNon-existent export 'resolve' is imported from __vite-browser-external
✓ 33 modules transformed.
Generated an empty chunk: "worker.js"
[crx:manifest-post] unable to parse manifest code
error during build:
Error: unable to parse manifest code
    at Object.decodeManifest (/Users/jefry.pozo/Documents/DevEnv/projects/npm/rollup-plugin-chrome-extension/dist/index.cjs:115:11)
    at Object.generateBundle (/Users/jefry.pozo/Documents/DevEnv/projects/npm/rollup-plugin-chrome-extension/dist/index.cjs:3107:40)
    at /Users/jefry.pozo/Documents/DevEnv/projects/npm/tailwind-bug/node_modules/rollup/dist/shared/rollup.js:22779:37
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
    Memory: 56.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 99.0
    Safari: 15.0
  npmPackages:
    rollup-plugin-chrome-extension: 4.0.1-18 => 4.0.1-22 
    vite: ^2.9.1 => 2.9.1
```

### Severity

blocking all usage of RPCE

**Comment by jpozo20** [comment]
Closed with pull #281
