### ISSUE TITLE
Push reloader is broken: "Uncaught FirebaseError"

### ISSUE THREAD

**Issue by njreid** [extend-chrome/rollup-plugin-chrome-extension#30]
**Describe the bug**
The automatic reload functionality is broken, and not entirely sure how to fix this issue.

**To Reproduce**
1. Invoke the npm watch script, (`rollup -c -w`) 
2. I see the following console log messages in the background.html console:

`reloader-sw-13ddda07.js:245 Uncaught FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).
    at getMissingValueError (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:2090:32)
    at extractAppConfig (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:2071:27)
    at Component.instanceFactory (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:3117:13)
    at Provider.getOrInitializeService (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:816:43)
    at Provider.getImmediate (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:720:37)
    at Component.factoryMethod [as instanceFactory] (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:5305:72)
    at Provider.getOrInitializeService (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:816:43)
    at Provider.getImmediate (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:720:37)
    at FirebaseAppImpl._getService (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:1252:53)
    at FirebaseAppImpl.messaging (chrome-extension://baofmnngiegejbkmjldhlojijmfkpolh/assets/reloader-sw-13ddda07.js:1461:43)`

**Expected behavior**
The background script should automatically reload.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
- Browser: Chrome 81.0.4044.138
- rollup-plugin-chrome-extension version 2.2.0

**Additional context**

**Comment by jacksteamdev** [comment]
@njreid Thanks for reporting this issue! Looks like Firebase is acting up again. 😕

I suggest using the simple reloader for now. The only practical difference is that it will cause the background page not to go inactive.

```js
import { chromeExtension, simpleReloader } from 'rollup-plugin-chrome-extension'
```

**Comment by jacksteamdev** [comment]
This error is happening in the service worker that we add to support FCM.

Firebase does not detect the environment correctly and thinks this is a normal page, not a service worker. This has been a problem before, and I'm not satisfied with the way Firebase has performed over the months for this use case.

I'm going to explore another solution for the push reloader.

**Comment by njreid** [comment]
Thanks very much Jack, I found the simpleReloader and that's working nicely.
Really appreciate the work you've put into this loader. I was banging my head against a Webpack-based Chrome Extension boilerplate until I remember how much I hate Webpack. Rollup is just so much more intuitive for me, and your plugin works beautifully!

**Comment by jacksteamdev** [comment]
@njreid Thanks for your kind words. I, too, started on this project because I didn't like working with Webpack. 😉 Good to hear that the simple reloader is working for you.

I'm going to reopen this issue until the push reloader is fixed, or we decide to remove it. 

FYI, I've just released a new version that fixes a occasional issue with the simple reloader.

**Comment by jacksteamdev** [comment]
I've removed the push reloader in v3, so I'm closing this issue.
